services:
  # gateway:
  #   build:
  #     context: ./gateway
  #     dockerfile: ./cmd/Dockerfile
  #   networks:
  #     - tc-news
  #   ports:
  #     - "8080:80"

  subscription:
    build:
      context: ./subscribe
      dockerfile: ./cmd/Dockerfile
    ports:
      - "8081:8080"
    networks:
      - tc-news
    depends_on:
      subscribe-db:
        condition: service_started
  subscribe-db:
    image: "postgres:16"
    ports:
      - "5432:5432"
    networks:
      - tc-news
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  # vote:
  #   build:
  #     context: ./vote
  #     dockerfile: ./cmd/Dockerfile
  # vote-db:
  #   image: "postgres:16"
  #

  post:
    build:
      context: ./post
      dockerfile: ./cmd/Dockerfile
    ports:
      - "8083:8080"
    networks:
      - tc-news
    depends_on:
      post-db:
        condition: service_started
  post-db:
    image: "postgres:16"
    networks:
      - tc-news
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  comment:
    build:
      context: ./comment
      dockerfile: ./cmd/Dockerfile
    ports:
      - "8084:8080"
    networks:
      - tc-news
    depends_on:
      comment-db:
        condition: service_started
  comment-db:
    networks:
      - tc-news
    image: "postgres:16"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  auth:
    build:
      context: ./auth
      dockerfile: ./cmd/Dockerfile
    networks:
      - tc-news
    ports:
      - "8085:8080"
  auth-db:
    image: "redis"
    networks:
      - tc-news
  auth-postgres-db:
    image: "postgres:16"
    networks:
      - tc-news
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  kafka-service:
    image: apache/kafka:latest
    networks:
      - tc-news
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data

networks:
  tc-news:
