basePath: /
definitions:
  main.User:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  main.UserCreate:
    properties:
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for creating, reading, updating, and deleting users.
  title: User Service API
  version: "3.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Creates a new user
      parameters:
      - description: User payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.UserCreate'
      responses:
        "201":
          description: User created
        "400":
          description: Invalid body
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a user
      tags:
      - users
  /users/{id}:
    delete:
      description: Deletes a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: User deleted
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete a user
      tags:
      - users
    get:
      description: Retrieves a single user by their ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.User'
        "401":
          description: Invalid user id
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get a user by ID
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Updates an existing user's name
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated user payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.UserCreate'
      responses:
        "200":
          description: User updated
        "400":
          description: Invalid body
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update a user
      tags:
      - users
swagger: "2.0"
