apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db-service
  namespace: tc-news
spec:
  ports:
    - port: 5432
  selector:
    app: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
  namespace: tc-news
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      hostname: db
      containers:
        - name: db
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          image: postgres
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "50m"
          ports:
            - containerPort: 5432
