// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: subscribe/subscribe.proto

package subscribepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSubscribersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscribersRequest) Reset() {
	*x = GetSubscribersRequest{}
	mi := &file_subscribe_subscribe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscribersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribersRequest) ProtoMessage() {}

func (x *GetSubscribersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_subscribe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribersRequest.ProtoReflect.Descriptor instead.
func (*GetSubscribersRequest) Descriptor() ([]byte, []int) {
	return file_subscribe_subscribe_proto_rawDescGZIP(), []int{0}
}

func (x *GetSubscribersRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type GetSubscribersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscribersResponse) Reset() {
	*x = GetSubscribersResponse{}
	mi := &file_subscribe_subscribe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscribersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribersResponse) ProtoMessage() {}

func (x *GetSubscribersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_subscribe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribersResponse.ProtoReflect.Descriptor instead.
func (*GetSubscribersResponse) Descriptor() ([]byte, []int) {
	return file_subscribe_subscribe_proto_rawDescGZIP(), []int{1}
}

func (x *GetSubscribersResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_subscribe_subscribe_proto protoreflect.FileDescriptor

const file_subscribe_subscribe_proto_rawDesc = "" +
	"\n" +
	"\x19subscribe/subscribe.proto\x12\tsubscribe\"0\n" +
	"\x15GetSubscribersRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"3\n" +
	"\x16GetSubscribersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds2i\n" +
	"\x10SubscribeService\x12U\n" +
	"\x0eGetSubscribers\x12 .subscribe.GetSubscribersRequest\x1a!.subscribe.GetSubscribersResponseB)Z'github.com/timmyjinks/proto/subscribepbb\x06proto3"

var (
	file_subscribe_subscribe_proto_rawDescOnce sync.Once
	file_subscribe_subscribe_proto_rawDescData []byte
)

func file_subscribe_subscribe_proto_rawDescGZIP() []byte {
	file_subscribe_subscribe_proto_rawDescOnce.Do(func() {
		file_subscribe_subscribe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscribe_subscribe_proto_rawDesc), len(file_subscribe_subscribe_proto_rawDesc)))
	})
	return file_subscribe_subscribe_proto_rawDescData
}

var file_subscribe_subscribe_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_subscribe_subscribe_proto_goTypes = []any{
	(*GetSubscribersRequest)(nil),  // 0: subscribe.GetSubscribersRequest
	(*GetSubscribersResponse)(nil), // 1: subscribe.GetSubscribersResponse
}
var file_subscribe_subscribe_proto_depIdxs = []int32{
	0, // 0: subscribe.SubscribeService.GetSubscribers:input_type -> subscribe.GetSubscribersRequest
	1, // 1: subscribe.SubscribeService.GetSubscribers:output_type -> subscribe.GetSubscribersResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_subscribe_subscribe_proto_init() }
func file_subscribe_subscribe_proto_init() {
	if File_subscribe_subscribe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscribe_subscribe_proto_rawDesc), len(file_subscribe_subscribe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscribe_subscribe_proto_goTypes,
		DependencyIndexes: file_subscribe_subscribe_proto_depIdxs,
		MessageInfos:      file_subscribe_subscribe_proto_msgTypes,
	}.Build()
	File_subscribe_subscribe_proto = out.File
	file_subscribe_subscribe_proto_goTypes = nil
	file_subscribe_subscribe_proto_depIdxs = nil
}
